# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19zSNwEmGV7mD2h4q3RgCZ1gv556lf2EH
"""

# app.py
# ============================================================
# Main entry for the Streamlit multi-page app.
# Pages are automatically discovered from the /pages folder.
# ============================================================

import streamlit as st

st.set_page_config(
    page_title="Fake News Detection",
    page_icon="📰",
    layout="wide"
)

# Initialize shared session state keys (used across pages)
if "input_text" not in st.session_state:
    st.session_state["input_text"] = ""
if "prediction" not in st.session_state:
    # prediction will store: {"label": int, "probs": [p_fake, p_real]}
    st.session_state["prediction"] = None

st.title("Fake News Detection App")
st.write(
    "Use the sidebar to navigate:\n"
    "- Introduction\n"
    "- Input\n"
    "- Result\n"
)

st.info(
    "Tip: Start with the **Input** page to paste news text, then view the **Result** page."
)