# -*- coding: utf-8 -*-
"""1_Introduction.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YiTmkS_BzDkFuMkL1DwpHz-6e2coM3Fr
"""

# pages/1_Introduction.py
# ============================================================
# Page 1: Introduction
# ============================================================

import base64
import os
import streamlit as st

st.set_page_config(page_title="Introduction - Fake News Detection", layout="wide")

def set_background(image_path: str):
    """
    Sets a background image if it exists; otherwise uses a clean gradient.
    """
    if os.path.exists(image_path):
        with open(image_path, "rb") as f:
            data = f.read()
        b64 = base64.b64encode(data).decode()
        st.markdown(
            f"""
            <style>
            .stApp {{
                background: url("data:image/png;base64,{b64}") no-repeat center center fixed;
                background-size: cover;
            }}
            .content-card {{
                background: rgba(255, 255, 255, 0.88);
                padding: 24px;
                border-radius: 16px;
                max-width: 980px;
                margin: 0 auto;
                box-shadow: 0 8px 26px rgba(0,0,0,0.12);
            }}
            </style>
            """,
            unsafe_allow_html=True,
        )
    else:
        # Fallback: professional gradient background
        st.markdown(
            """
            <style>
            .stApp {
                background: linear-gradient(135deg, #0f172a 0%, #111827 50%, #0b1220 100%);
            }
            .content-card {
                background: rgba(255, 255, 255, 0.92);
                padding: 24px;
                border-radius: 16px;
                max-width: 980px;
                margin: 0 auto;
                box-shadow: 0 8px 26px rgba(0,0,0,0.18);
            }
            </style>
            """,
            unsafe_allow_html=True,
        )

# Optional: place an image at assets/bg_intro.png
set_background("assets/bg_intro.png")

# Session defaults (in case user opens this page first)
if "input_text" not in st.session_state:
    st.session_state["input_text"] = ""
if "prediction" not in st.session_state:
    st.session_state["prediction"] = None

st.markdown('<div class="content-card">', unsafe_allow_html=True)

st.title("Fake News Detection System")
st.write(
    """
This application classifies news text into two categories:

- **FAKE = 0**
- **REAL = 1**

The goal is to help demonstrate how modern NLP models can detect misinformation patterns in text.
"""
)

st.subheader("Model Used")
st.write(
    """
- **RoBERTa-base** fine-tuned for binary text classification.
- Suitable for news-style language and robust in many NLP benchmarks.
"""
)

st.subheader("How It Works (High Level)")
st.write(
    """
1. You paste a headline or article text.
2. The app tokenizes your text using the RoBERTa tokenizer.
3. The RoBERTa model outputs probabilities for **FAKE** and **REAL**.
4. The app displays the predicted label and confidence.
"""
)

st.subheader("What to Do Next")
st.write("Open the **Input** page from the sidebar, paste your text, and click **Predict**.")

st.markdown("</div>", unsafe_allow_html=True)